### ISSUE TITLE
[Failing Test] ci-k8sio-file-promo-mirrors

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/k8s.io#7391] opened 2024-10-10 07:39 UTC
https://testgrid.k8s.io/sig-k8s-infra-k8sio#ci-k8sio-file-promo-mirrors
https://testgrid.k8s.io/sig-release-releng-blocking#ci-k8sio-file-promo-mirrors

/sig release 

Failed for a long time: https://github.com/kubernetes/k8s.io/issues/5358. 

> {"component":"entrypoint","file":"sigs.k8s.io/prow/pkg/entrypoint/run.go:169","func":"sigs.k8s.io/prow/pkg/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 2h0m0s timeout","severity":"error","time":"2024-10-10T04:35:35Z"}

Is this just a timeout?

**Comment by pacoxu** [comment] 2024-10-11 01:19
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-k8sio-file-promo-mirrors/1844296402704797696
- Test started yesterday at 4:38 PM failed after 2h29m33s.

timeout is fixed. The new failure is 
```
level=warning msg="error copying file: error uploading \"s3://test-artifacts-k8s-io-us-east-2/binaries/kops/1.25.4/darwin/amd64/kops\": AccessDenied: Access Denied\n\tstatus code: 403, request id: CP9917QTQMMXT6Y6, host id: skOu88oeTzOaO+7oAwf3hlHZW3IE0UU2m0v6rycL/Xj6IB0xz6B769d8otOeZDrZFUmO2dqR028="
COPY "gs://k8s-artifacts-prod/binaries/kops/1.25.4/darwin/amd64/kops.sha256" to "s3://test-artifacts-k8s-io-us-east-2/binaries/kops/1.25.4/darwin/amd64/kops.sha256"


error uploading "s3://test-artifacts-k8s-io-ap-southeast-1/binaries/cloud-provider-aws/v1.31.0/windows/amd64/ecr-credential-provider-windows-amd64.sha256": AccessDenied: Access Denied
	status code: 403, request id: F4DCG18C6Z9BCHA6, host id: /pHk3yXbHMADq30XVK1Zod3ZRp5OfZz0qtDgATEVUBhm9zLbfc8M1ofuhBZ1ZNSAIYTfM436xvE=
level=fatal msg="run `kpromo run files`: error uploading \"s3://test-artifacts-k8s-io-us-east-2/binaries/kops/1.25.4/darwin/amd64/kops\": AccessDenied: Access Denied\n\tstatus code: 403, request id: CP9917QTQMMXT6Y6, host id: skOu88oeTzOaO+7oAwf3hlHZW3IE0UU2m0v6rycL/Xj6IB0xz6B769d8otOeZDrZFUmO2dqR028="
```

**Comment by ameukam** [comment] 2024-12-18 00:48
Duplicate of:
  - https://github.com/kubernetes/k8s.io/issues/7505
  
  
/close

**Closed by ameukam** 2024-12-18 00:48 UTC
Labels: sig/release
