### ISSUE TITLE
k8s cluster cannot get the metrics-server image

### ISSUE THREAD

**Issue by tooboredtocode** [kubernetes/k8s.io#3194] opened 2021-12-15 14:14 UTC
(copied from [metrics-server#919](https://github.com/kubernetes-sigs/metrics-server/issues/919))

**What happened**:
k8s cluster cannot get the metrics-server image:
````
Events:
  Type     Reason          Age                   From               Message
  ----     ------          ----                  ----               -------
  Normal   Scheduled       2m45s                 default-scheduler  Successfully assigned kube-system/metrics-server-5b6dd75459-jqdfn to lkexxxxx-xxxxx-xxxxxxxxxxxx
  Normal   SandboxChanged  2m43s                 kubelet            Pod sandbox changed, it will be killed and re-created.
  Warning  Failed          2m3s (x3 over 2m44s)  kubelet            Failed to pull image "k8s.gcr.io/metrics-server/metrics-server:v0.5.2": rpc error: code = Unknown desc = Error response from daemon: error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content=\"initial-scale=1, minimum-scale=1, width=device-width\">\n  <title>Error 403 (Forbidden)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>403.</b> <ins>That’s an error.</ins>\n  <p>Your client does not have permission to get URL <code>/v2/metrics-server/metrics-server/manifests/v0.5.2</code> from this server.  <ins>That’s all we know.</ins>\n"
  Warning  Failed          2m3s (x3 over 2m44s)  kubelet            Error: ErrImagePull
  Normal   BackOff         87s (x7 over 2m42s)   kubelet            Back-off pulling image "k8s.gcr.io/metrics-server/metrics-server:v0.5.2"
  Warning  Failed          87s (x7 over 2m42s)   kubelet            Error: ImagePullBackOff
  Normal   Pulling         72s (x4 over 2m44s)   kubelet            Pulling image "k8s.gcr.io/metrics-server/metrics-server:v0.5.2"
````

**What you expected to happen**:
the cluster should be able to pull the image

**Anything else we need to know?**:

**Environment**:
- Kubernetes distribution (GKE, EKS, Kubeadm, the hard way, etc.): LKE
- Container Network Setup (flannel, calico, etc.): calico
- Kubernetes version (use `kubectl version`): 1.22.3

- Metrics Server manifest

<details>
  <summary>spoiler for Metrics Server manifest:</summary>

````yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: metrics-server
  name: metrics-server
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    k8s-app: metrics-server
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: system:aggregated-metrics-reader
rules:
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  - nodes
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    k8s-app: metrics-server
  name: system:metrics-server
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - nodes/stats
  - namespaces
  - configmaps
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    k8s-app: metrics-server
  name: metrics-server-auth-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: metrics-server
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    k8s-app: metrics-server
  name: metrics-server:system:auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: metrics-server
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    k8s-app: metrics-server
  name: system:metrics-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:metrics-server
subjects:
- kind: ServiceAccount
  name: metrics-server
  namespace: kube-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: metrics-server
  name: metrics-server
  namespace: kube-system
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    k8s-app: metrics-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: metrics-server
  name: metrics-server
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: metrics-server
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        k8s-app: metrics-server
    spec:
      containers:
      - args:
        - --cert-dir=/tmp
        - --secure-port=4443
        - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
        - --kubelet-use-node-status-port
        - --metric-resolution=15s
        - --kubelet-insecure-tls
        image: k8s.gcr.io/metrics-server/metrics-server:v0.5.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /livez
            port: https
            scheme: HTTPS
          periodSeconds: 10
        name: metrics-server
        ports:
        - containerPort: 4443
          name: https
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: https
            scheme: HTTPS
          initialDelaySeconds: 20
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
        volumeMounts:
        - mountPath: /tmp
          name: tmp-dir
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-cluster-critical
      serviceAccountName: metrics-server
      volumes:
      - emptyDir: {}
        name: tmp-dir
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  labels:
    k8s-app: metrics-server
  name: v1beta1.metrics.k8s.io
spec:
  group: metrics.k8s.io
  groupPriorityMinimum: 100
  insecureSkipTLSVerify: true
  service:
    name: metrics-server
    namespace: kube-system
  version: v1beta1
  versionPriority: 100
````

</details>

- Kubelet config:

<details>
  <summary>spoiler for Kubelet config:</summary>

  not relevant

</details>

- Metrics server logs:

<details>
  <summary>spoiler for Metrics Server logs:</summary>

 no logs

</details>

- Status of Metrics API:
<details>
  <summary>spolier for Status of Metrics API:</summary>

  ```
  Name:         v1beta1.metrics.k8s.io
Namespace:
Labels:       k8s-app=metrics-server
Annotations:  <none>
API Version:  apiregistration.k8s.io/v1
Kind:         APIService
Metadata:
  Creation Timestamp:  2021-12-01T22:07:55Z
  Managed Fields:
    API Version:  apiregistration.k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
        f:labels:
          .:
          f:k8s-app:
      f:spec:
        f:group:
        f:groupPriorityMinimum:
        f:insecureSkipTLSVerify:
        f:service:
          .:
          f:name:
          f:namespace:
          f:port:
        f:version:
        f:versionPriority:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2021-12-01T22:07:55Z
    API Version:  apiregistration.k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"Available"}:
            f:lastTransitionTime:
            f:message:
            f:reason:
            f:status:
    Manager:         kube-apiserver
    Operation:       Update
    Subresource:     status
    Time:            2021-12-07T18:11:59Z
  Resource Version:  933652
  UID:               cd4f87a8-5cb9-4de3-8333-50bf207e680b
Spec:
  Group:                     metrics.k8s.io
  Group Priority Minimum:    100
  Insecure Skip TLS Verify:  true
  Service:
    Name:            metrics-server
    Namespace:       kube-system
    Port:            443
  Version:           v1beta1
  Version Priority:  100
Status:
  Conditions:
    Last Transition Time:  2021-12-15T11:44:50Z
    Message:               endpoints for service/metrics-server in "kube-system" have no addresses with port name "https"
    Reason:                MissingEndpoints
    Status:                False
    Type:                  Available
Events:                    <none>
  ```

  

</details>

/kind bug

**Comment by ameukam** [comment] 2021-12-16 10:57
@tooboredtocode we are aware of network issues with Linode: https://github.com/kubernetes/k8s.io/issues/2028

We use Google Container Registry for k8s.gcr.io and since it's a managed service we don't have control on network infrastructure of this service.
I'll strongly advise to raise an issue with Linode support so they can investigate the underlying problem with Google Network Team.

/lifecycle frozen

**Comment by zhaow-de** [comment] 2021-12-30 22:22
It is a confirmed Linode/LKE specific issue, which has nothing to do with this repo. I paste the response from Linode support here, just to help the others encountering the same issue and ended up here like I did:

> Our team has been recently made aware of an issue with the /64 IPv6 subnet assigned to Frankfurt. Due to a technical miscommunication, Google has placed this range on its blocklist. For regular Linodes, this can be circumvented by forcing IPv4, or using a /64 routed range but at the moment the best workaround for LKE users is to use a cluster in another region. Since this has a severe impact on those users (LKE users in Frankfurt) We've already reached out to Google-- they've escalated this matter internally and have confirmed with us that they are working on resolving the issue.

**Comment by ameukam** [comment] 2022-01-03 09:03
@zhaow-de Thanks for the update. I'll close this issue. Feel free to open a new issue if any action need to be done by us.

/close

**Closed** 2022-01-03 09:03 UTC
Labels: kind/bug, lifecycle/frozen, sig/k8s-infra
