### ISSUE TITLE
Increase BQ resource limits

### ISSUE THREAD

**Issue by bernokl** [kubernetes/k8s.io#2024] opened 2021-05-10 01:52 UTC
In the k8s-infra-ii-sandbox project I try to run the following query against a dataset with a single column and 11 million records and a second table with only 40k records:
```
select NET.IPV4_TO_INT64(ipv4_c_ip) as ip,
NET.IP_TO_STRING (ipv4_c_ip),
int64_field_2 as asn,
string_field_4 as asn_name
from `k8s-infra-ii-sandbox.k8s_artifacts_gcslogs_appspot.distinct_appspot_ip_netip_1`,
`k8s-infra-ii-sandbox.k8s_artifacts_gcslogs_appspot.ip2asn`
where
RANGE_BUCKET(
NET.IPV4_TO_INT64(ipv4_c_ip),
[
NET.IPV4_TO_INT64(NET.IP_FROM_STRING(string_field_0)),
NET.IPV4_TO_INT64(NET.IP_FROM_STRING(string_field_1))
]
)=1;
 
Unfortunately the job can not finish and results in the following error:
```
Error running query
Query exceeded resource limits. This query used 74811 CPU seconds but would charge only 30M Analysis bytes. This exceeds the ratio supported by the on-demand pricing model. Please consider moving this workload to the flat-rate reservation pricing model, which does not have this limit. 74811 CPU seconds were used, and this query must use less than 7600 CPU seconds.
```

Can I please request help with this?

**Comment by ameukam** [comment] 2021-05-10 18:33
@Riaankl @bboreham 
```
from `k8s-infra-ii-sandbox.k8s_artifacts_gcslogs_appspot.distinct_appspot_ip_netip_1`,
```

`distinct_appspot_ip_netip_1` seems deleted. I can't reproduce your issue.

**Comment by spiffxp** [comment] 2021-05-10 18:52
Can you provide a reproduceable query?

I'm reading up on the pricing models, and am trying to find reference to the "ratio" that's being discussed here.  I interpret the error to mean the query is using a lot of CPU for little data.

- https://cloud.google.com/bigquery/docs/best-practices-costs
- https://cloud.google.com/bigquery/pricing
- https://cloud.google.com/bigquery/docs/reservations-intro

**Comment by spiffxp** [comment] 2021-05-10 18:54
I'm wondering if you've tried these tips?
- https://cloud.google.com/bigquery/docs/best-practices-costs#materialize_query_results_in_stages
- https://cloud.google.com/bigquery/docs/best-practices-costs#partition_data_by_date

**Comment by bernokl** [comment] 2021-05-10 19:03
I put the table back it should work now https://github.com/kubernetes/k8s.io/issues/2024#issuecomment-837110845

**Comment by bernokl** [comment] 2021-05-10 19:04
> Can you provide a reproduceable query?
> 
> I'm reading up on the pricing models, and am trying to find reference to the "ratio" that's being discussed here. I interpret the error to mean the query is using a lot of CPU for little data.
> 
> * https://cloud.google.com/bigquery/docs/best-practices-costs
> * https://cloud.google.com/bigquery/pricing
> * https://cloud.google.com/bigquery/docs/reservations-intro

yes, I thought so to, I changed the query to remove all string functions but still get the same result
select ip,
c_ip,
int64_field_2 as asn,
string_field_4 as asn_name
from `k8s-infra-ii-sandbox.k8s_artifacts_gcslogs_appspot.distinct_appspot_ip_int`,
`k8s-infra-ii-sandbox.k8s_artifacts_gcslogs_appspot.ip2asn_int`
where
ip >= f0_ and ip <= f1_;

**Comment by bernokl** [comment] 2021-05-11 03:36
I went to look at reservations and see minimum purchase is $3000
![image](https://user-images.githubusercontent.com/6902524/117754530-9de35480-b26e-11eb-8ff1-46298e297c55.png)

**Comment by justinsb** [comment] 2021-05-13 16:30
I will try to upload the tool that uploads the logs and tags the CIDRs

**Comment by hh** [comment] 2021-05-13 18:36
Thanks @justinsb!

**Comment by spiffxp** [comment] 2021-05-20 22:17
/close
I have no idea how you got tagged in @bboreham but you said what I was trying to say way more succinctly, so thank you.

I'm closing this as I've heard no chatter about this lately, so I'm going to assume you've found a way to construct more reasonable queries or datasets.

**Closed** 2021-05-20 22:17 UTC
Labels: wg/k8s-infra
