### ISSUE TITLE
audit followup: some boskos projects missing IAM

### ISSUE THREAD

**Issue by thockin** [kubernetes/k8s.io#1662] opened 2021-02-16 23:51 UTC
k8s-infra-e2e-boskos-41+ are missing the IAM binding:

```
    {
      "members": [
        "group:k8s-infra-prow-viewers@kubernetes.io"
      ],
      "role": "roles/viewer"
    }
```

**Comment by spiffxp** [comment] 2021-02-17 21:37
/kind bug
/sig testing
/area prow
/priority important-soon
/milestone v1.21
/assign
this requires a re-run of `infra/gcp/prow/ensure-e2e-projects.sh`

**Comment by spiffxp** [comment] 2021-02-17 23:37
/retitle audit followup: some boskos projects missing IAM

**Comment by spiffxp** [comment] 2021-02-25 04:14
/close
Closing as dupe of https://github.com/kubernetes/k8s.io/issues/1661#issuecomment-785547221

**Closed** 2021-02-25 04:14 UTC
Labels: area/prow, kind/bug, priority/important-soon, sig/testing, wg/k8s-infra
